// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-CoZZAnPObW_hWvvPtZgrDmAL79gKFo',
    appId: '1:847279297462:web:ecfdaa1542033325812717',
    messagingSenderId: '847279297462',
    projectId: 'chatapp-4e80e',
    authDomain: 'chatapp-4e80e.firebaseapp.com',
    storageBucket: 'chatapp-4e80e.appspot.com',
    measurementId: 'G-XXZ0LWND25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2P2vSpeDKbZ2FUkgMJ9b3Vz6GQsrnz58',
    appId: '1:847279297462:android:35f85d79fae63754812717',
    messagingSenderId: '847279297462',
    projectId: 'chatapp-4e80e',
    storageBucket: 'chatapp-4e80e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0h91qaZcvc18XqnOWUYicZgy8HzOiDxA',
    appId: '1:847279297462:ios:e836c4a5b3fee039812717',
    messagingSenderId: '847279297462',
    projectId: 'chatapp-4e80e',
    storageBucket: 'chatapp-4e80e.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0h91qaZcvc18XqnOWUYicZgy8HzOiDxA',
    appId: '1:847279297462:ios:746616353069a18e812717',
    messagingSenderId: '847279297462',
    projectId: 'chatapp-4e80e',
    storageBucket: 'chatapp-4e80e.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
